# Generated by Django 5.1.6 on 2025-02-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_author_remove_book_author_book_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="author",
            unique_together={("first_name", "last_name")},
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(related_name="books", to="service.author"),
        ),
    ]
