# Generated by Django 5.1.6 on 2025-02-18 19:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramuser",
            name="chat_id",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="unique_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
